"""Configuration constants for deterministic inventory calculations."""

from __future__ import annotations

EWMA_ALPHA = 0.35
LEVEL_SHIFT_RATIO = 1.5
LEVEL_SHIFT_WEEKS = 4
LEVEL_SHIFT_MIN_SHARE = 0.75
MIN_LEVEL_BASELINE_WEEKS = 4
OUTLIER_MAD_MULTIPLIER = 4.0

TARGET_HISTORY_WEEKS = 12
CONFIDENCE_BASE = 0.30
CONFIDENCE_HISTORY_WEIGHT = 0.55
CONFIDENCE_VOLATILITY_WEIGHT = 0.60
CONFIDENCE_MISSING_PENALTY = 0.08
CONFIDENCE_LEVEL_SHIFT_PENALTY = 0.08
CONFIDENCE_THRESHOLD = 0.60
MIN_CONFIDENCE = 0.0
MAX_CONFIDENCE = 1.0

INTENT_AMBIGUITY_MARGIN = 0.15
QA_AMBIGUOUS_SKU_CONFIDENCE = 0.45
QA_UNKNOWN_CONFIDENCE = 0.20
QA_MISSING_PARAMETER_CONFIDENCE = 0.50
QA_INTENT_BASE_CONFIDENCE = 0.72
QA_INTENT_MATCH_WEIGHT = 0.08
QA_MAX_CONFIDENCE = 0.98
SCENARIO_DEMAND_INCREASE = 1.20

DAYS_IN_MONTH = 30
DAYS_IN_QUARTER = 90
DAYS_IN_HALF_YEAR = 180
DAYS_IN_YEAR = 365
